spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/quotebox
          jwk-set-uri: http://localhost:8180/auth/realms/quotebox/protocol/openid-connect/certs

      #      client:
      #        registration:
      #          keycloak:
      #            client-id: quotebox-client
      #            authorization-grant-type: authorization_code
      #            scope: openid
      #        provider:
      #          keycloak:
      #            issuer-uri: http://localhost:8180/auth/realms/quotebox
      #            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG