spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/quotebox
          jwk-set-uri: http://localhost:8180/auth/realms/quotebox/protocol/openid-connect/certs

logging:
  level:
    org.springframework: DEBUG