openapi: 3.0.3
info:
  title: Quote API
  description: Quote API
  version: 0.1.0
paths:
  /quote/random:
    get:
      summary: Get a random quote
      operationId: v1RandomQuote
      parameters:
        - in: query
          name: author
          schema:
            type: string
        - in: query
          name: tags
          schema:
            type: array
            items:
              type: string
      responses:
        '303':
          description: Link to a random quote
          headers:
            Location:
              schema:
                type: string
  /quote/{id}:
    get:
      summary: Get a specific quote
      operationId: v1GetQuote
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: The requested quote
          content:
            application/json:
              schema:
                $ref: quote.yaml#/Quote
  /quote:
    post:
      summary: Add a new quote
      operationId: v1AddQuote
      requestBody:
        description: Quote to add
        required: true
        content:
          application/json:
            schema:
              $ref: quote.yaml#/Quote
      responses:
        '201':
          description: Created
